### ISSUE TITLE
Strange missing reference 2.4.1

### ISSUE THREAD

**Issue by soehler** [FasterXML/jackson-jr#18]
Trying to do :  
```java
Object ob = new Ob();
JSON.std.write(ob, new File("somefile.json"));
```

Where:
```java
public class Ob {
	
	private String Name;
	private String Address;
	
	public Ob(){
		
	}
	
	public String getName() {
		return Name;
	}
	public void setNome(String name) {
		Name = name;
	}
	public String getAddress() {
		return Address;
	}
	public void setAddress(String address) {
		Address = address;
	}	
}  
```
Using:  
```xml
<dependency> 
  	<groupId>com.fasterxml.jackson.jr</groupId> 
  	<artifactId>jackson-jr-all</artifactId> 
  	<version>2.4.1</version> 
</dependency>
```
Eclipse says Error:  
"The type com.fasterxml.jackson.jr.private.JsonGenerator cannot be resolved. It is indirectly referenced from required .class files"

**Comment by kjkrum** [comment]
What do you mean by "unintended imports"?  Are we talking about classes that you don't want anyone to use?  Rethink the package structure so the classes don't need to be public.  If that's impossible, then just document that they shouldn't be used.  Don't screw around with invalid package names.  That just screams "use GSON."

**Comment by cowtowncoder** [comment]
@kjkrum These are private dependencies shaded in package from other library (Jackson streaming). They are not part of jackson-jr, and they are not to be imported. Unintended import means things like IDE auto-completion offering use of such classes. Making such classes private is, alas, impossible, given that they are in separate package, and there is no mechanism to give limited access (friend etc).

As to invalid package names, use of internal names that are valid in bytecode, but invalid in source is well-established practice by various code generation tools (use of `$`). There is valid use case here, and I'd appreciate you trying to understand the case before making patronizing blanket statements based on false assumptions.

**Comment by kjkrum** [comment]
If both of the leading IDEs think you're doing something sketchy, then you're probably doing something sketchy.  (And FYI, `$` is valid in source for both class and package names.)

**Comment by cowtowncoder** [comment]
@kjkrum I am not fond of the approach of using `private` but needs must. I am open to better solutions.

But back to the original report: I am not yet convinced that use of private causes the problem.
I have seen similar reports where IDE claims a dependency is missing for other components that shade libs (like asm). It could be due to either actual problem by shade plugin (or its use), or by IDE.

If there was a way to easily reproduce the issue outside of Eclipse (or perhaps with test project), I can locally re-build the jar and see if replacing `private` would solve the problem or not. If not, it would be good to know what the problem is.

**Comment by amadeoas** [comment]
Eclipse does not like the use of the world private as part of the package name.

You can see this by specifying the package with private as import:

    import com.fasterxml.jackson.core.private.Versioned;

in which case eclipse highlight the word private in red as error.

**Comment by kjkrum** [comment]
It's not just Eclipse.  This is simply an [illegal package name](http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).  Oracle's recommendation is to add an underscore to the reserved word, i.e., 'com.fasterxml.jackson.core.private_.Versioned'.  This wouldn't address the structural issues, but at least it would make the library usable.

**Comment by cowtowncoder** [comment]
@amadeoas This is intentional because you should try to import anything from that package. Import would be an error and use of `private` is about the only way I know of to prevent it (aside from forcing users to use something like OSGi to prevent visibility via class loader and avoid shading)

I do not know why Eclipse chooses to complain since it is strictly speaking none of its business at that point.

If this is problematic, the work-around is to use `jackson-jr-objects` (which does not use shading) instead of `jackson-jr-all` (which does).

**Comment by cayhorstmann** [comment]
I am trying it with jackson-jr-objects, and I am getting the same error.

**Comment by cowtowncoder** [comment]
@cayhorstmann I don't see how that would be possible as it does not use shading, as there is no `private ` package referenced by anything.

However, given that uber-jar (jackson-jr-all) and regular one have same Java packages, including both could effectively hide non-shaded version?

**Comment by cayhorstmann** [comment]
It is possible if one doesn't know what one is doing :-) In my case, the error was caused by a missing jackson-core JAR. I didn't find the documentation at https://github.com/FasterXML/jackson-jr all that clear for non-Maven users, and I had to read it several times to realize that I needed another JAR.

In fact, I am still not clear whether I am better off with jackson-jr-objects and jackson-core or with jackson-jr-all, or whether it doesn't matter.

**Comment by cowtowncoder** [comment]
@cayhorstmann This could definitely use more documentation, but the distinction should essentially be that of whether you benefit from a single-jar deployment or not. The default choice with modern built systems should be `jackson-jr-objects`, non-shaded version; `jackson-jr-all` being more useful if jars need to be included manually (like old Ant builds or such). Especially so because often build system is used to create the single jar deployment, and it can just fetch dependant jars.

**Comment by amadeoas** [comment]
@cowtowncoder thank you. Using jackson-jr-objects removes the problem

**Comment by cowtowncoder** [comment]
As per #17, I decided to forego use of `private`, so with 2.7, this should not be a problem any more.
