### ISSUE TITLE
`java.util.Date` can not be serialized as `long`, only (non-configurable) textual

### ISSUE THREAD

**Issue by gpiancastelli** [FasterXML/jackson-jr#29]
I need to serialize dates in their canonical milliseconds representation; however, when an object with a `java.util.Date` property is serialized, the produced JSON contains dates as formatted strings, e.g. `"Tue Oct 27 17:48:29 CET 2015"`. I checked out the documentation to see if there is some kind of feature to activate, or some kind of annotation to put on the relevant getter method, but, alas, no luck.

Is there a way to obtain the milliseconds representation for dates in Jackson Jr.?

Note that deserialization of milliseconds into `java.util.Date` objects work just fine.

**Comment by cowtowncoder** [comment]
Sounds like this could be a new `JSON.Feature` (`WRITE_DATES_AS_LONG`?): currently `date.toString()` is indeed used. Deserializer however accepts `long`s.
Adding the new feature should be easy enough and would apply to `java.util.Date` and `java.util.Calendar`.

Change to default formatting would be separate possible addition; it would be bit more work, so I'd have to see if and how to do that. Sounds like a useful thing to have, although also opens the way for more complicated handling (what about `TimeZone` used?), perhaps ability for custom handlers.
And at some point it's necessary to define where to stop addition of features, to keep library small.
But one step at a time makes sense, starting with ability to serialize dates as timestamps.

**Comment by cowtowncoder** [comment]
First things first: added `JSON.Feature.WRITE_DATES_AS_TIMESTAMP`, enabling of which allows timestamp serialization.

Question of if and how to configure `DateFormat` to use is trickier, and I am not sure how far to even go there. java.util.Date is flawed by design unfortunately, and a better model would probably be to allow some way of registering custom writer/reader so calling code could choose how it wants to handle this.
