### ISSUE TITLE
how to stream read a huge JSON file?

### ISSUE THREAD

**Issue by TaurusNing** [FasterXML/jackson-jr#59]
is that possible?

**Comment by cowtowncoder** [comment]
In future, please use Jackson user mailing list for usage questions.

But quick answer is that no, there is no incremental reading at this point. Standard `jackson-databind` (or streaming) are better choices for that.

**Comment by TaurusNing** [comment]
Thank you.
I'm not familiar with mailing list, sorry for bothering.

**Comment by cowtowncoder** [comment]
No prob, it's a google group:

https://groups.google.com/forum/#!forum/jackson-user

I also filed #60 to remember that such a feature might be useful. I won't promise it would be added, mostly since it is difficult to know how far to extend this package (compared to standard jackson). But as far as ideas go, it is good one.

**Comment by TaurusNing** [comment]
Agreed.
and it's not hard to add this feature.

**Comment by cowtowncoder** [comment]
@TaurusNing Correct, technically speaking streaming api allows reading just fine, and then jr binder could relatively easily use that.
