### ISSUE TITLE
help: primer on deserializing JSON into objects

### ISSUE THREAD

**Issue by cmusser** [FasterXML/jackson-jr#68]
Hi,

I have objects similar to the following
```
public final class Route
        implements Postable {
    private String description;
    private final double distance;
    private final String name;
...
}
```
that I'd like to deserialize from a JSON web response. The responses always contain arrays of these. At a high level, it looks like the way to do this is creating a custom subclass of `JSONReader`. In looking through the Javadoc, though, I couldn't figure out how to use it. Is there a tutorial or conceptual overview on how to use this class, and other related one?

**Comment by cowtowncoder** [comment]
@cmusser You probably should use full Jackson (`jackson-databind`) in this case, since by default onl `public` fields will be used (as an alternative to public getters/setters).
Jackson-jr 2.10 will add a mechanism to add custom `ValueReader`s, which you could use, but earlier versions do not allow much customization.

There is `2.10.0.pr2` (2nd pre-release version) out, of course, and one of unit tests should have an example of how to register custom `ValueReader`s, if you are interested. Full 2.10.0 is planned to be released by end of September.

**Comment by cmusser** [comment]
This application is for Android, so I used jr, instead of databind (I think there was a recommendation to that effect on the portal page). Maybe I'll wait for the 2.10 release. In the meantime, where would an example of that be in the docs for the upcoming stuff?

**Comment by cowtowncoder** [comment]
Ah. Ok yes. 

As to docs, remain to be written -- I will start by writing an overview of jackson 2.10, which includes jackson-jr changes -- but `com.fasterxml.jackson.jr.ob.impl.CustomValueReadersTest` (and `CustomValueWritersTest`). would show how to add custom value readers and writers, something like:

```java
        JSON json = JSON.std
                .with(new CustomReaders()); // ReaderWriterProvider impl
        CustomValue v = json.beanFrom(CustomValue.class, "123");
```

and to read an array thereof you'd use one of

```java
      CustomValue[] values = json.arrayOfFrom(CustomValue.class, source);
      List<CustomValue> valueList = json.listOfFrom(CustomValue.class, source);
```
