### ISSUE TITLE
Case-insensitive property, enum deserialization should be supported

### ISSUE THREAD

**Issue by MikeDombo** [FasterXML/jackson-jr#80]
Full Jackson has the option ACCEPT_CASE_INSENSITIVE_PROPERTIES and ACCEPT_CASE_INSENSITIVE_ENUMS, these or similar options should be available for jackson-jr.

**Comment by cowtowncoder** [comment]
Another excellent idea!

**Comment by MikeDombo** [comment]
Closed by #82

**Comment by cowtowncoder** [comment]
Merged but does not work in 3.0 (`master`) due to implementation differences. Need to think of what to do there: 3.0 would actually have efficient mechanism for case-insensitive matching via `PropertyNameMatcher`... but needs to be wired. There's an existing comment that suggests caching might be challenging as well.

**Comment by cowtowncoder** [comment]
Was able to make master/3.0 work as well with `PropertyNameMatcher`.
